class SuraNames {
  static const List<Map<String, String>> surahNames = [
    {'ar': 'الفاتحة', 'tr': 'Fatiha', 'en': 'Al-Fatiha'},
    {'ar': 'البقرة', 'tr': 'Bakara', 'en': 'Al-Baqarah'},
    {'ar': 'آل عمران', 'tr': 'Âl-i İmrân', 'en': 'Ali Imran'},
    {'ar': 'النساء', 'tr': 'Nisâ', 'en': 'An-Nisa'},
    {'ar': 'المائدة', 'tr': 'Mâide', 'en': 'Al-Ma\'ida'},
    {'ar': 'الأنعام', 'tr': 'En\'âm', 'en': 'Al-An\'am'},
    {'ar': 'الأعراف', 'tr': 'A\'râf', 'en': 'Al-A\'raf'},
    {'ar': 'الأنفال', 'tr': 'Enfâl', 'en': 'Al-Anfal'},
    {'ar': 'التوبة', 'tr': 'Tevbe', 'en': 'At-Tawbah'},
    {'ar': 'يونس', 'tr': 'Yûnus', 'en': 'Yunus'},
    {'ar': 'هود', 'tr': 'Hûd', 'en': 'Hud'},
    {'ar': 'يوسف', 'tr': 'Yûsuf', 'en': 'Yusuf'},
    {'ar': 'الرعد', 'tr': 'Ra\'d', 'en': 'Ar-Ra\'d'},
    {'ar': 'إبراهيم', 'tr': 'İbrâhîm', 'en': 'Ibrahim'},
    {'ar': 'الحجر', 'tr': 'Hicr', 'en': 'Al-Hijr'},
    {'ar': 'النحل', 'tr': 'Nahl', 'en': 'An-Nahl'},
    {'ar': 'الإسراء', 'tr': 'İsrâ', 'en': 'Al-Isra'},
    {'ar': 'الكهف', 'tr': 'Kehf', 'en': 'Al-Kahf'},
    {'ar': 'مريم', 'tr': 'Meryem', 'en': 'Maryam'},
    {'ar': 'طه', 'tr': 'Tâhâ', 'en': 'Ta-Ha'},
    {'ar': 'الأنبياء', 'tr': 'Enbiyâ', 'en': 'Al-Anbiya'},
    {'ar': 'الحج', 'tr': 'Hac', 'en': 'Al-Hajj'},
    {'ar': 'المؤمنون', 'tr': 'Mü\'minûn', 'en': 'Al-Mu\'minun'},
    {'ar': 'النور', 'tr': 'Nûr', 'en': 'An-Nur'},
    {'ar': 'الفرقان', 'tr': 'Furkân', 'en': 'Al-Furqan'},
    {'ar': 'الشعراء', 'tr': 'Şu\'arâ', 'en': 'Ash-Shu\'ara'},
    {'ar': 'النمل', 'tr': 'Neml', 'en': 'An-Naml'},
    {'ar': 'القصص', 'tr': 'Kasas', 'en': 'Al-Qasas'},
    {'ar': 'العنكبوت', 'tr': 'Ankebût', 'en': 'Al-Ankabut'},
    {'ar': 'الروم', 'tr': 'Rûm', 'en': 'Ar-Rum'},
    {'ar': 'لقمان', 'tr': 'Lokmân', 'en': 'Luqman'},
    {'ar': 'السجدة', 'tr': 'Secde', 'en': 'As-Sajdah'},
    {'ar': 'الأحزاب', 'tr': 'Ahzâb', 'en': 'Al-Ahzab'},
    {'ar': 'سبأ', 'tr': 'Sebe', 'en': 'Saba'},
    {'ar': 'فاطر', 'tr': 'Fâtır', 'en': 'Fatir'},
    {'ar': 'يس', 'tr': 'Yâsîn', 'en': 'Ya-Sin'},
    {'ar': 'الصافات', 'tr': 'Sâffât', 'en': 'As-Saffat'},
    {'ar': 'ص', 'tr': 'Sâd', 'en': 'Sad'},
    {'ar': 'الزمر', 'tr': 'Zümer', 'en': 'Az-Zumar'},
    {'ar': 'غافر', 'tr': 'Mü\'min', 'en': 'Ghafir'},
    {'ar': 'فصلت', 'tr': 'Fussilet', 'en': 'Fussilat'},
    {'ar': 'الشورى', 'tr': 'Şûrâ', 'en': 'Ash-Shura'},
    {'ar': 'الزخرف', 'tr': 'Zuhruf', 'en': 'Az-Zukhruf'},
    {'ar': 'الدخان', 'tr': 'Duhân', 'en': 'Ad-Dukhan'},
    {'ar': 'الجاثية', 'tr': 'Câsiye', 'en': 'Al-Jathiyah'},
    {'ar': 'الأحقاف', 'tr': 'Ahkâf', 'en': 'Al-Ahqaf'},
    {'ar': 'محمد', 'tr': 'Muhammed', 'en': 'Muhammad'},
    {'ar': 'الفتح', 'tr': 'Fetih', 'en': 'Al-Fath'},
    {'ar': 'الحجرات', 'tr': 'Hucurât', 'en': 'Al-Hujurat'},
    {'ar': 'ق', 'tr': 'Kâf', 'en': 'Qaf'},
    {'ar': 'الذاريات', 'tr': 'Zâriyât', 'en': 'Adh-Dhariyat'},
    {'ar': 'الطور', 'tr': 'Tûr', 'en': 'At-Tur'},
    {'ar': 'النجم', 'tr': 'Necm', 'en': 'An-Najm'},
    {'ar': 'القمر', 'tr': 'Kamer', 'en': 'Al-Qamar'},
    {'ar': 'الرحمن', 'tr': 'Rahmân', 'en': 'Ar-Rahman'},
    {'ar': 'الواقعة', 'tr': 'Vâkıa', 'en': 'Al-Waqi\'ah'},
    {'ar': 'الحديد', 'tr': 'Hadîd', 'en': 'Al-Hadid'},
    {'ar': 'المجادلة', 'tr': 'Mücâdele', 'en': 'Al-Mujadilah'},
    {'ar': 'الحشر', 'tr': 'Haşr', 'en': 'Al-Hashr'},
    {'ar': 'الممتحنة', 'tr': 'Mümtehine', 'en': 'Al-Mumtahanah'},
    {'ar': 'الصف', 'tr': 'Saff', 'en': 'As-Saff'},
    {'ar': 'الجمعة', 'tr': 'Cum\'a', 'en': 'Al-Jumu\'ah'},
    {'ar': 'المنافقون', 'tr': 'Münâfikûn', 'en': 'Al-Munafiqun'},
    {'ar': 'التغابن', 'tr': 'Teğâbün', 'en': 'At-Taghabun'},
    {'ar': 'الطلاق', 'tr': 'Talâk', 'en': 'At-Talaq'},
    {'ar': 'التحريم', 'tr': 'Tahrîm', 'en': 'At-Tahrim'},
    {'ar': 'الملك', 'tr': 'Mülk', 'en': 'Al-Mulk'},
    {'ar': 'القلم', 'tr': 'Kalem', 'en': 'Al-Qalam'},
    {'ar': 'الحاقة', 'tr': 'Hâkka', 'en': 'Al-Haqqah'},
    {'ar': 'المعارج', 'tr': 'Meâric', 'en': 'Al-Ma\'arij'},
    {'ar': 'نوح', 'tr': 'Nûh', 'en': 'Nuh'},
    {'ar': 'الجن', 'tr': 'Cin', 'en': 'Al-Jinn'},
    {'ar': 'المزمل', 'tr': 'Müzzemmil', 'en': 'Al-Muzzammil'},
    {'ar': 'المدثر', 'tr': 'Müddessir', 'en': 'Al-Muddaththir'},
    {'ar': 'القيامة', 'tr': 'Kıyâme', 'en': 'Al-Qiyamah'},
    {'ar': 'الإنسان', 'tr': 'İnsân', 'en': 'Al-Insan'},
    {'ar': 'المرسلات', 'tr': 'Mürselât', 'en': 'Al-Mursalat'},
    {'ar': 'النبأ', 'tr': 'Nebe', 'en': 'An-Naba'},
    {'ar': 'النازعات', 'tr': 'Nâziât', 'en': 'An-Nazi\'at'},
    {'ar': 'عبس', 'tr': 'Abese', 'en': 'Abasa'},
    {'ar': 'التكوير', 'tr': 'Tekvîr', 'en': 'At-Takwir'},
    {'ar': 'الانفطار', 'tr': 'İnfitâr', 'en': 'Al-Infitar'},
    {'ar': 'المطففين', 'tr': 'Mutaffifîn', 'en': 'Al-Mutaffifin'},
    {'ar': 'الانشقاق', 'tr': 'İnşikâk', 'en': 'Al-Inshiqaq'},
    {'ar': 'البروج', 'tr': 'Burûc', 'en': 'Al-Buruj'},
    {'ar': 'الطارق', 'tr': 'Târık', 'en': 'At-Tariq'},
    {'ar': 'الأعلى', 'tr': 'A\'lâ', 'en': 'Al-A\'la'},
    {'ar': 'الغاشية', 'tr': 'Ğâşiye', 'en': 'Al-Ghashiyah'},
    {'ar': 'الفجر', 'tr': 'Fecr', 'en': 'Al-Fajr'},
    {'ar': 'البلد', 'tr': 'Beled', 'en': 'Al-Balad'},
    {'ar': 'الشمس', 'tr': 'Şems', 'en': 'Ash-Shams'},
    {'ar': 'الليل', 'tr': 'Leyl', 'en': 'Al-Layl'},
    {'ar': 'الضحى', 'tr': 'Duhâ', 'en': 'Ad-Dhuha'},
    {'ar': 'الشرح', 'tr': 'İnşirâh', 'en': 'Ash-Sharh'},
    {'ar': 'التين', 'tr': 'Tîn', 'en': 'At-Tin'},
    {'ar': 'العلق', 'tr': 'Alak', 'en': 'Al-Alaq'},
    {'ar': 'القدر', 'tr': 'Kadir', 'en': 'Al-Qadr'},
    {'ar': 'البينة', 'tr': 'Beyyine', 'en': 'Al-Bayyinah'},
    {'ar': 'الزلزلة', 'tr': 'Zilzâl', 'en': 'Az-Zalzalah'},
    {'ar': 'العاديات', 'tr': 'Âdiyât', 'en': 'Al-Adiyat'},
    {'ar': 'القارعة', 'tr': 'Kâria', 'en': 'Al-Qari\'ah'},
    {'ar': 'التكاثر', 'tr': 'Tekâsür', 'en': 'At-Takathur'},
    {'ar': 'العصر', 'tr': 'Asr', 'en': 'Al-Asr'},
    {'ar': 'الهمزة', 'tr': 'Hümeze', 'en': 'Al-Humazah'},
    {'ar': 'الفيل', 'tr': 'Fîl', 'en': 'Al-Fil'},
    {'ar': 'قريش', 'tr': 'Kureyş', 'en': 'Quraysh'},
    {'ar': 'الماعون', 'tr': 'Mâûn', 'en': 'Al-Ma\'un'},
    {'ar': 'الكوثر', 'tr': 'Kevser', 'en': 'Al-Kawthar'},
    {'ar': 'الكافرون', 'tr': 'Kâfirûn', 'en': 'Al-Kafirun'},
    {'ar': 'النصر', 'tr': 'Nasr', 'en': 'An-Nasr'},
    {'ar': 'المسد', 'tr': 'Tebbet', 'en': 'Al-Masad'},
    {'ar': 'الإخلاص', 'tr': 'İhlâs', 'en': 'Al-Ikhlas'},
    {'ar': 'الفلق', 'tr': 'Felak', 'en': 'Al-Falaq'},
    {'ar': 'الناس', 'tr': 'Nâs', 'en': 'An-Nas'},
  ];

  static String getSuraName(int suraIndex, String locale) {
    if (suraIndex < 0 || suraIndex >= surahNames.length) return '';
    
    switch (locale) {
      case 'ar':
        return surahNames[suraIndex]['ar'] ?? '';
      case 'tr':
        return surahNames[suraIndex]['tr'] ?? '';
      case 'en':
      default:
        return surahNames[suraIndex]['en'] ?? '';
    }
  }

  static int getTotalSuras() => surahNames.length;
}