class SuraNames {
  static const List<Map<String, String>> surahNames = [
    {
      'ar': 'الفاتحة',
      'tr': 'Fâtiha',
      'en': 'Al-Fatihah',
      'ur': 'الفاتحہ',
      'fa': 'فاتحه',
      'id': 'Al-Fatihah',
      'ms': 'Al-Fatihah',
      'bn': 'আল-ফাতিহা',
      'fr': 'Al-Fatiha',
      'hi': 'अल-फ़ातिहा',
      'uz': 'Fotiha',
      'ru': 'Аль-Фатиха',
      'es': 'Al-Fatiha',
      'pt': 'Al-Fatiha',
      'de': 'Al-Fatiha',
      'it': 'Al-Fatiha',
      'zh': '开端章',
      'sw': 'Al-Fatiha',
      'ja': 'アル・ファーティハ',
      'ko': '알파티하',
      'th': 'อัลฟาติฮะฮ์',
    },
    {
      'ar': 'البقرة',
      'tr': 'Bakara',
      'en': 'Al-Baqarah',
      'ur': 'البقرہ',
      'fa': 'بقره',
      'id': 'Al-Baqarah',
      'ms': 'Al-Baqarah',
      'bn': 'আল-বাকারা',
      'fr': 'Al-Baqara',
      'hi': 'अल-बक़रह',
      'uz': 'Baqara',
      'ru': 'Аль-Бакара',
      'es': 'La vaca',
      'pt': 'A Vaca',
      'de': 'Die Kuh',
      'it': 'La vacca',
      'zh': '黄牛章',
      'sw': 'Ng’ombe',
      'ja': 'アル・バカラ',
      'ko': '알바까라',
      'th': 'อัลบะเกาะเราะฮ์',
    },
    {
      'ar': 'آل عمران',
      'tr': 'Âl-i İmrân',
      'en': 'Aal-Imran',
      'ur': 'اٰل عمران',
      'fa': 'آل عمران',
      'id': 'Ali Imran',
      'ms': 'Ali Imran',
      'bn': 'আলে-ইমরান',
      'fr': 'Aal-Imran',
      'hi': 'आल-इमरान',
      'uz': 'Oli Imron',
      'ru': 'Али Имран',
      'es': 'La familia de Imran',
      'pt': 'A Família de Imran',
      'de': 'Die Familie Imran',
      'it': 'La famiglia di Imran',
      'zh': '伊姆兰的家属章',
      'sw': 'Imran',
      'ja': 'アール・イムラーン',
      'ko': '알이므란',
      'th': 'อาลิอิมรอน',
    },
    {
      'ar': 'النساء',
      'tr': 'Nisâ',
      'en': 'An-Nisa',
      'ur': 'النساء',
      'fa': 'نساء',
      'id': 'An-Nisa',
      'ms': 'An-Nisa',
      'bn': 'আন-নিসা',
      'fr': 'An-Nisa',
      'hi': 'अन्-निसा',
      'uz': 'Niso',
      'ru': 'Ан-Ниса',
      'es': 'Las mujeres',
      'pt': 'As Mulheres',
      'de': 'Die Frauen',
      'it': 'Le donne',
      'zh': '妇女章',
      'sw': 'Wanawake',
      'ja': 'アン・ニサー',
      'ko': '안니사',
      'th': 'อันนิซาอ์',
    },
    {
      'ar': 'المائدة',
      'tr': 'Mâide',
      'en': 'Al-Ma\'idah',
      'ur': 'المائدہ',
      'fa': 'مائده',
      'id': 'Al-Ma’idah',
      'ms': 'Al-Ma’idah',
      'bn': 'আল-মায়িদা',
      'fr': 'Al-Maida',
      'hi': 'अल-माइदा',
      'uz': 'Moida',
      'ru': 'Аль-Маида',
      'es': 'La mesa servida',
      'pt': 'A Mesa Servida',
      'de': 'Der Tisch',
      'it': 'La tavola',
      'zh': '筵席章',
      'sw': 'Meza',
      'ja': 'アル・マーイダ',
      'ko': '알마이다',
      'th': 'อัลมาอิดะฮ์',
    },
    {
      'ar': 'الأنعام',
      'tr': 'En’âm',
      'en': 'Al-An’am',
      'ur': 'الانعام',
      'fa': 'انعام',
      'id': 'Al-An’am',
      'ms': 'Al-An’am',
      'bn': 'আল-আনআম',
      'fr': 'Al-Anam',
      'hi': 'अल-अनआम',
      'uz': 'An’om',
      'ru': 'Аль-Анам',
      'es': 'El ganado',
      'pt': 'O Gado',
      'de': 'Das Vieh',
      'it': 'Il bestiame',
      'zh': '牲畜章',
      'sw': 'Mifugo',
      'ja': 'アル・アナーム',
      'ko': '알아나암',
      'th': 'อัลอันอาม',
    },
    {
      'ar': 'الأعراف',
      'tr': 'A’râf',
      'en': 'Al-A\'raf',
      'ur': 'الاعراف',
      'fa': 'اعراف',
      'id': 'Al-A’raf',
      'ms': 'Al-A’raf',
      'bn': 'আল-আরাফ',
      'fr': 'Al-Araf',
      'hi': 'अल-आराफ़',
      'uz': 'A’rof',
      'ru': 'Аль-Араф',
      'es': 'Las alturas',
      'pt': 'As Alturas',
      'de': 'Die Höhen',
      'it': 'Le alture',
      'zh': '高处章',
      'sw': 'Vilimani',
      'ja': 'アル・アアーラーフ',
      'ko': '알아아라프',
      'th': 'อัลอะอ์รอฟ',
    },
    {
      'ar': 'الأنفال',
      'tr': 'Enfâl',
      'en': 'Al-Anfal',
      'ur': 'الانفال',
      'fa': 'انفال',
      'id': 'Al-Anfal',
      'ms': 'Al-Anfal',
      'bn': 'আল-আনফাল',
      'fr': 'Al-Anfal',
      'hi': 'अल-अनफ़ाल',
      'uz': 'Anfol',
      'ru': 'Аль-Анфаль',
      'es': 'El botín',
      'pt': 'O Espólio',
      'de': 'Die Beute',
      'it': 'Il bottino',
      'zh': '战利品章',
      'sw': 'Ng’ombe wa Vita',
      'ja': 'アル・アンファール',
      'ko': '알안팔',
      'th': 'อัลอันฟาล',
    },
    {
      'ar': 'التوبة',
      'tr': 'Tevbe',
      'en': 'At-Tawbah',
      'ur': 'التوبہ',
      'fa': 'توبه',
      'id': 'At-Taubah',
      'ms': 'At-Taubah',
      'bn': 'আত-তাওবা',
      'fr': 'At-Tawba',
      'hi': 'अत-तौबा',
      'uz': 'Tavba',
      'ru': 'Ат-Тауба',
      'es': 'El arrepentimiento',
      'pt': 'O Arrependimento',
      'de': 'Die Reue',
      'it': 'Il pentimento',
      'zh': '忏悔章',
      'sw': 'Toba',
      'ja': 'アット・タウバ',
      'ko': '앗타우바',
      'th': 'อัตเตาบะฮ์',
    },
    {
      'ar': 'يونس',
      'tr': 'Yûnus',
      'en': 'Yunus',
      'ur': 'یونس',
      'fa': 'یونس',
      'id': 'Yunus',
      'ms': 'Yunus',
      'bn': 'ইউনুস',
      'fr': 'Yunus',
      'hi': 'यूनुस',
      'uz': 'Yunus',
      'ru': 'Юнус',
      'es': 'Jonás',
      'pt': 'Jonas',
      'de': 'Jonas',
      'it': 'Giona',
      'zh': '优努斯章',
      'sw': 'Yunus',
      'ja': 'ユヌス',
      'ko': '유누스',
      'th': 'ยูนุส',
    },
    {
      'ar': 'هود',
      'tr': 'Hûd',
      'en': 'Hud',
      'ur': 'ہود',
      'fa': 'هود',
      'id': 'Hud',
      'ms': 'Hud',
      'bn': 'হুদ',
      'fr': 'Hud',
      'hi': 'हूद',
      'uz': 'Hud',
      'ru': 'Худ',
      'es': 'Hud',
      'pt': 'Hud',
      'de': 'Hud',
      'it': 'Hud',
      'zh': '呼德章',
      'sw': 'Hud',
      'ja': 'フード',
      'ko': '후드',
      'th': 'ฮูด',
    },
    {
      'ar': 'يوسف',
      'tr': 'Yûsuf',
      'en': 'Yusuf',
      'ur': 'یوسف',
      'fa': 'یوسف',
      'id': 'Yusuf',
      'ms': 'Yusuf',
      'bn': 'ইউসুফ',
      'fr': 'Yusuf',
      'hi': 'यूसुफ',
      'uz': 'Yusuf',
      'ru': 'Юсуф',
      'es': 'José',
      'pt': 'José',
      'de': 'Josef',
      'it': 'Giuseppe',
      'zh': '优素福章',
      'sw': 'Yusufu',
      'ja': 'ユスフ',
      'ko': '유수프',
      'th': 'ยูซุฟ',
    },
    {
      'ar': 'الرعد',
      'tr': 'Ra’d',
      'en': 'Ar-Ra’d',
      'ur': 'الرعد',
      'fa': 'رعد',
      'id': 'Ar-Ra’d',
      'ms': 'Ar-Ra’d',
      'bn': 'আর-রাদ',
      'fr': 'Ar-Ra\'d',
      'hi': 'अर-रअद',
      'uz': 'Ra’d',
      'ru': 'Ар-Раад',
      'es': 'El trueno',
      'pt': 'O Trovão',
      'de': 'Der Donner',
      'it': 'Il tuono',
      'zh': '雷霆章',
      'sw': 'Radi',
      'ja': 'アル・ラアド',
      'ko': '알라아드',
      'th': 'อัรรอดอ์',
    },
    {
      'ar': 'إبراهيم',
      'tr': 'İbrâhîm',
      'en': 'Ibrahim',
      'ur': 'ابراہیم',
      'fa': 'ابراهیم',
      'id': 'Ibrahim',
      'ms': 'Ibrahim',
      'bn': 'ইবরাহিম',
      'fr': 'Ibrahim',
      'hi': 'इब्राहीम',
      'uz': 'Ibrohim',
      'ru': 'Ибрахим',
      'es': 'Abraham',
      'pt': 'Abraão',
      'de': 'Abraham',
      'it': 'Abramo',
      'zh': '易卜拉欣章',
      'sw': 'Ibrahim',
      'ja': 'イブラーヒーム',
      'ko': '이브라힘',
      'th': 'อิบรอฮีม',
    },
    {
      'ar': 'الحجر',
      'tr': 'Hicr',
      'en': 'Al-Hijr',
      'ur': 'الحجر',
      'fa': 'حجر',
      'id': 'Al-Hijr',
      'ms': 'Al-Hijr',
      'bn': 'আল-হিজর',
      'fr': 'Al-Hijr',
      'hi': 'अल-हिज्र',
      'uz': 'Hijr',
      'ru': 'Аль-Хиджр',
      'es': 'La piedra',
      'pt': 'A Pedra',
      'de': 'Der Felsen',
      'it': 'La roccia',
      'zh': '石谷章',
      'sw': 'Hijr',
      'ja': 'アル・ヒジュル',
      'ko': '알히즈르',
      'th': 'อัลฮิจร',
    },
    {
      'ar': 'النحل',
      'tr': 'Nahl',
      'en': 'An-Nahl',
      'ur': 'النحل',
      'fa': 'نحل',
      'id': 'An-Nahl',
      'ms': 'An-Nahl',
      'bn': 'আন-নাহল',
      'fr': 'An-Nahl',
      'hi': 'अन-नहल',
      'uz': 'Nahl',
      'ru': 'Ан-Нахль',
      'es': 'Las abejas',
      'pt': 'As Abelhas',
      'de': 'Die Bienen',
      'it': 'Le api',
      'zh': '蜜蜂章',
      'sw': 'Nyuki',
      'ja': 'アン・ナフル',
      'ko': '안나흘',
      'th': 'อันนะห์ล',
    },
    {
      'ar': 'الإسراء',
      'tr': 'İsrâ',
      'en': 'Al-Isra',
      'ur': 'الاسراء',
      'fa': 'اسراء',
      'id': 'Al-Isra',
      'ms': 'Al-Isra',
      'bn': 'আল-ইসরা',
      'fr': 'Al-Isra',
      'hi': 'अल-इसरा',
      'uz': 'Isro',
      'ru': 'Аль-Исра',
      'es': 'El viaje nocturno',
      'pt': 'A Viagem Noturna',
      'de': 'Die Nachtreise',
      'it': 'Il viaggio notturno',
      'zh': '夜行章',
      'sw': 'Safari ya Usiku',
      'ja': 'アル・イスラー',
      'ko': '알이스라',
      'th': 'อัลอิสรออ์',
    },
    {
      'ar': 'الكهف',
      'tr': 'Kehf',
      'en': 'Al-Kahf',
      'ur': 'الکہف',
      'fa': 'کهف',
      'id': 'Al-Kahf',
      'ms': 'Al-Kahf',
      'bn': 'আল-কাহফ',
      'fr': 'Al-Kahf',
      'hi': 'अल-कह्फ',
      'uz': 'Kahf',
      'ru': 'Аль-Кахф',
      'es': 'La cueva',
      'pt': 'A Caverna',
      'de': 'Die Höhle',
      'it': 'La caverna',
      'zh': '山洞章',
      'sw': 'Pango',
      'ja': 'アル・カフ',
      'ko': '알까흐프',
      'th': 'อัลกะฮ์ฟ',
    },
    {
      'ar': 'مريم',
      'tr': 'Meryem',
      'en': 'Maryam',
      'ur': 'مریم',
      'fa': 'مریم',
      'id': 'Maryam',
      'ms': 'Maryam',
      'bn': 'মারইয়াম',
      'fr': 'Maryam',
      'hi': 'मरयम',
      'uz': 'Maryam',
      'ru': 'Марьям',
      'es': 'María',
      'pt': 'Maria',
      'de': 'Maria',
      'it': 'Maria',
      'zh': '麦尔彦章',
      'sw': 'Maryam',
      'ja': 'マルヤム',
      'ko': '마르얌',
      'th': 'มัรยัม',
    },
    {
      'ar': 'طه',
      'tr': 'Tâhâ',
      'en': 'Taha',
      'ur': 'طٰہٰ',
      'fa': 'طه',
      'id': 'Taha',
      'ms': 'Taha',
      'bn': 'তা-হা',
      'fr': 'Taha',
      'hi': 'ता-हा',
      'uz': 'Toha',
      'ru': 'Та-Ха',
      'es': 'Ta Ha',
      'pt': 'Ta-Ha',
      'de': 'Ta-Ha',
      'it': 'Ta-Ha',
      'zh': '塔哈章',
      'sw': 'Taha',
      'ja': 'ター・ハー',
      'ko': '타하',
      'th': 'ฏอฮา',
    },
    {
      'ar': 'الأنبياء',
      'tr': 'Enbiyâ',
      'en': 'The Prophets',
      'ur': 'الأنبياء',
      'fa': 'انبیا',
      'id': 'Al-Anbiya',
      'ms': 'Al-Anbiya',
      'bn': 'আম্বিয়া',
      'fr': 'Les Prophètes',
      'hi': 'अंबिया',
      'uz': 'Paygʻambarlar',
      'ru': 'Пророки',
      'es': 'Los Profetas',
      'pt': 'Os Profetas',
      'de': 'Die Propheten',
      'it': 'I Profeti',
      'zh': '众先知',
      'sw': 'Manabii',
      'ja': '預言者たち',
      'ko': '예언자들',
      'th': 'ศาสดา',
    },
    {
      'ar': 'الحج',
      'tr': 'Hac',
      'en': 'The Pilgrimage',
      'ur': 'الحج',
      'fa': 'حج',
      'id': 'Al-Hajj',
      'ms': 'Al-Hajj',
      'bn': 'হজ্জ',
      'fr': 'Le Pèlerinage',
      'hi': 'हज',
      'uz': 'Haj',
      'ru': 'Паломничество',
      'es': 'La Peregrinación',
      'pt': 'A Peregrinação',
      'de': 'Die Pilgerfahrt',
      'it': 'Il Pellegrinaggio',
      'zh': '朝觐',
      'sw': 'Hija',
      'ja': '巡礼',
      'ko': '순례',
      'th': 'การแสวงบุญ',
    },
    {
      'ar': 'المؤمنون',
      'tr': 'Mü’minûn',
      'en': 'The Believers',
      'ur': 'المؤمنون',
      'fa': 'مؤمنون',
      'id': 'Al-Mu\'minun',
      'ms': 'Al-Mu\'minun',
      'bn': 'মুমিনুন',
      'fr': 'Les Croyants',
      'hi': 'मोमिनून',
      'uz': 'Moʻminlar',
      'ru': 'Верующие',
      'es': 'Los Creyentes',
      'pt': 'Os Crentes',
      'de': 'Die Gläubigen',
      'it': 'I Credenti',
      'zh': '信士们',
      'sw': 'Waumini',
      'ja': '信仰者たち',
      'ko': '믿는자들',
      'th': 'ผู้ศรัทธา',
    },
    {
      'ar': 'النور',
      'tr': 'Nûr',
      'en': 'The Light',
      'ur': 'النور',
      'fa': 'نور',
      'id': 'An-Nur',
      'ms': 'An-Nur',
      'bn': 'নূর',
      'fr': 'La Lumière',
      'hi': 'नूर',
      'uz': 'Nur',
      'ru': 'Свет',
      'es': 'La Luz',
      'pt': 'A Luz',
      'de': 'Das Licht',
      'it': 'La Luce',
      'zh': '光明',
      'sw': 'Nuru',
      'ja': '光',
      'ko': '빛',
      'th': 'แสงสว่าง',
    },
    {
      'ar': 'الفرقان',
      'tr': 'Furkân',
      'en': 'The Criterion',
      'ur': 'الفرقان',
      'fa': 'فرقان',
      'id': 'Al-Furqan',
      'ms': 'Al-Furqan',
      'bn': 'ফুরকান',
      'fr': 'Le Discernement',
      'hi': 'फ़ुरक़ान',
      'uz': 'Furqon',
      'ru': 'Различение',
      'es': 'El Criterio',
      'pt': 'O Critério',
      'de': 'Das Unterscheidungsvermögen',
      'it': 'Il Criterio',
      'zh': '准则',
      'sw': 'Furqani',
      'ja': '区別',
      'ko': '판단',
      'th': 'เกณฑ์',
    },
    {
      'ar': 'الشعراء',
      'tr': 'Şuarâ',
      'en': 'The Poets',
      'ur': 'الشعراء',
      'fa': 'شعرا',
      'id': 'Asy-Syu\'ara',
      'ms': 'Asy-Syu\'ara',
      'bn': 'শুয়ারা',
      'fr': 'Les Poètes',
      'hi': 'शायर',
      'uz': 'Shoirlar',
      'ru': 'Поэты',
      'es': 'Los Poetas',
      'pt': 'Os Poetas',
      'de': 'Die Dichter',
      'it': 'I Poeti',
      'zh': '诗人',
      'sw': 'Washairi',
      'ja': '詩人たち',
      'ko': '시인들',
      'th': 'กวี',
    },
    {
      'ar': 'النمل',
      'tr': 'Neml',
      'en': 'The Ant',
      'ur': 'النمل',
      'fa': 'نمل',
      'id': 'An-Naml',
      'ms': 'An-Naml',
      'bn': 'নামল',
      'fr': 'La Fourmi',
      'hi': 'चींटी',
      'uz': 'Chumoli',
      'ru': 'Муравей',
      'es': 'La Hormiga',
      'pt': 'A Formiga',
      'de': 'Die Ameise',
      'it': 'La Formica',
      'zh': '蚂蚁',
      'sw': 'Mchwa',
      'ja': 'アリ',
      'ko': '개미',
      'th': 'มด',
    },
    {
      'ar': 'القصص',
      'tr': 'Kasas',
      'en': 'The Stories',
      'ur': 'القصص',
      'fa': 'قصص',
      'id': 'Al-Qasas',
      'ms': 'Al-Qasas',
      'bn': 'কাসাস',
      'fr': 'Les Récits',
      'hi': 'क़सस',
      'uz': 'Qissalar',
      'ru': 'Истории',
      'es': 'Las Historias',
      'pt': 'As Histórias',
      'de': 'Die Geschichten',
      'it': 'Le Storie',
      'zh': '故事',
      'sw': 'Hadithi',
      'ja': '物語',
      'ko': '이야기들',
      'th': 'เรื่องราว',
    },
    {
      'ar': 'العنكبوت',
      'tr': 'Ankebût',
      'en': 'The Spider',
      'ur': 'العنكبوت',
      'fa': 'عنکبوت',
      'id': 'Al-Ankabut',
      'ms': 'Al-Ankabut',
      'bn': 'আনকাবুত',
      'fr': 'L’Araignée',
      'hi': 'मकड़ी',
      'uz': 'Oʻrka',
      'ru': 'Паук',
      'es': 'La Araña',
      'pt': 'A Aranha',
      'de': 'Die Spinne',
      'it': 'Il Ragno',
      'zh': '蜘蛛',
      'sw': 'Buibui',
      'ja': 'クモ',
      'ko': '거미',
      'th': 'แมงมุม',
    },
    {
      'ar': 'الروم',
      'tr': 'Rûm',
      'en': 'The Romans',
      'ur': 'الروم',
      'fa': 'روم',
      'id': 'Ar-Rum',
      'ms': 'Ar-Rum',
      'bn': 'রূম',
      'fr': 'Les Romains',
      'hi': 'रोम',
      'uz': 'Rimliklar',
      'ru': 'Римляне',
      'es': 'Los Romanos',
      'pt': 'Os Romanos',
      'de': 'Die Römer',
      'it': 'I Romani',
      'zh': '罗马人',
      'sw': 'Warumi',
      'ja': 'ローマ人',
      'ko': '로마인들',
      'th': 'ชาวโรมัน',
    },
    {
      'ar': 'لقمان',
      'tr': 'Lokmân',
      'en': 'Luqman',
      'ur': 'لقمان',
      'fa': 'لقمان',
      'id': 'Luqman',
      'ms': 'Luqman',
      'bn': 'লুকমান',
      'fr': 'Luqmân',
      'hi': 'लुक़मान',
      'uz': 'Luqmon',
      'ru': 'Лукман',
      'es': 'Luqman',
      'pt': 'Luqman',
      'de': 'Luqman',
      'it': 'Luqman',
      'zh': '鲁格曼',
      'sw': 'Luqman',
      'ja': 'ルクマン',
      'ko': '루크만',
      'th': 'ลูกมาน',
    },
    {
      'ar': 'السجدة',
      'tr': 'Secde',
      'en': 'The Prostration',
      'ur': 'السجدة',
      'fa': 'سجده',
      'id': 'As-Sajdah',
      'ms': 'As-Sajdah',
      'bn': 'সাজদাহ',
      'fr': 'La Prosternation',
      'hi': 'सज्दा',
      'uz': 'Sajda',
      'ru': 'Поклонение',
      'es': 'La Prosternación',
      'pt': 'A Prostração',
      'de': 'Die Niederwerfung',
      'it': 'La Prostrazione',
      'zh': '叩头',
      'sw': 'Kusujudu',
      'ja': '礼拝',
      'ko': '절',
      'th': 'การกราบ',
    },
    {
      'ar': 'الأحزاب',
      'tr': 'Ahzâb',
      'en': 'The Confederates',
      'ur': 'الأحزاب',
      'fa': 'احزاب',
      'id': 'Al-Ahzab',
      'ms': 'Al-Ahzab',
      'bn': 'আহযাব',
      'fr': 'Les Coalisés',
      'hi': 'अहज़ाब',
      'uz': 'Ahzob',
      'ru': 'Союзники',
      'es': 'Los Confederados',
      'pt': 'Os Confederados',
      'de': 'Die Verbündeten',
      'it': 'I Confederati',
      'zh': '同盟军',
      'sw': 'Washirika',
      'ja': '同盟軍',
      'ko': '동맹자들',
      'th': 'พันธมิตร',
    },
    {
      'ar': 'سبأ',
      'tr': 'Sebe',
      'en': 'Saba',
      'ur': 'سبأ',
      'fa': 'سبا',
      'id': 'Saba',
      'ms': 'Saba',
      'bn': 'সাবা',
      'fr': 'Saba',
      'hi': 'सबअ',
      'uz': 'Saba',
      'ru': 'Саба',
      'es': 'Saba',
      'pt': 'Sabá',
      'de': 'Saba',
      'it': 'Saba',
      'zh': '示巴',
      'sw': 'Sheba',
      'ja': 'シバ',
      'ko': '세바',
      'th': 'เชบา',
    },
    {
      'ar': 'فاطر',
      'tr': 'Fâtır',
      'en': 'The Originator',
      'ur': 'فاطر',
      'fa': 'فاطر',
      'id': 'Fatir',
      'ms': 'Fatir',
      'bn': 'ফাতির',
      'fr': 'Le Créateur',
      'hi': 'फ़ातिर',
      'uz': 'Yaratgan',
      'ru': 'Творец',
      'es': 'El Creador',
      'pt': 'O Criador',
      'de': 'Der Schöpfer',
      'it': 'Il Creatore',
      'zh': '创造者',
      'sw': 'Muumbaji',
      'ja': '創造者',
      'ko': '창조주',
      'th': 'ผู้สร้าง',
    },
    {
      'ar': 'يس',
      'tr': 'Yâsîn',
      'en': 'Ya-Sin',
      'ur': 'یس',
      'fa': 'یس',
      'id': 'Ya-Sin',
      'ms': 'Ya-Sin',
      'bn': 'ইয়াসিন',
      'fr': 'Ya-Sin',
      'hi': 'या-सीन',
      'uz': 'Yosin',
      'ru': 'Йа-Син',
      'es': 'Ya-Sin',
      'pt': 'Ya-Sin',
      'de': 'Ya-Sin',
      'it': 'Ya-Sin',
      'zh': '雅辛',
      'sw': 'Ya-Sin',
      'ja': 'ヤー・スィーン',
      'ko': '야신',
      'th': 'ยา-ซีน',
    },
    {
      'ar': 'الصافات',
      'tr': 'Sâffât',
      'en': 'Those who set the Ranks',
      'ur': 'الصافات',
      'fa': 'صافات',
      'id': 'As-Saffat',
      'ms': 'As-Saffat',
      'bn': 'সাফফাত',
      'fr': 'Les Rangés',
      'hi': 'साफ़्फ़ात',
      'uz': 'Saflar',
      'ru': 'Ряды',
      'es': 'Los que se alinean',
      'pt': 'Os que formam fileiras',
      'de': 'Die Aufgereihten',
      'it': 'Coloro che si allineano',
      'zh': '排列者',
      'sw': 'Wanaojiweka safu',
      'ja': '列を成す者',
      'ko': '줄지은 자들',
      'th': 'ผู้ที่จัดแถว',
    },
    {
      'ar': 'ص',
      'tr': 'Sâd',
      'en': 'Sad',
      'ur': 'ص',
      'fa': 'ص',
      'id': 'Sad',
      'ms': 'Sad',
      'bn': 'সাদ',
      'fr': 'Sad',
      'hi': 'साद',
      'uz': 'Sad',
      'ru': 'Сад',
      'es': 'Sad',
      'pt': 'Sad',
      'de': 'Sad',
      'it': 'Sad',
      'zh': '萨德',
      'sw': 'Sad',
      'ja': 'サード',
      'ko': '사드',
      'th': 'ซอด',
    },
    {
      'ar': 'الزمر',
      'tr': 'Zümer',
      'en': 'The Groups',
      'ur': 'الزمر',
      'fa': 'زمر',
      'id': 'Az-Zumar',
      'ms': 'Az-Zumar',
      'bn': 'জুমার',
      'fr': 'Les Groupes',
      'hi': 'ज़ुमर',
      'uz': 'Guruhlar',
      'ru': 'Группы',
      'es': 'Los Grupos',
      'pt': 'Os Grupos',
      'de': 'Die Gruppen',
      'it': 'I Gruppi',
      'zh': '群体',
      'sw': 'Makundi',
      'ja': 'グループ',
      'ko': '무리들',
      'th': 'กลุ่มคน',
    },
    {
      'ar': 'غافر',
      'tr': 'Mü’min (Ğâfir)',
      'en': 'The Forgiver',
      'ur': 'غافر',
      'fa': 'غافر',
      'id': 'Ghafir',
      'ms': 'Ghafir',
      'bn': 'গাফির',
      'fr': 'Le Pardonneur',
      'hi': 'ग़ाफ़िर',
      'uz': 'Kechiruvchi',
      'ru': 'Прощающий',
      'es': 'El Perdonador',
      'pt': 'O Perdoador',
      'de': 'Der Vergeber',
      'it': 'Il Perdonatore',
      'zh': '赦宥者',
      'sw': 'Msamehevu',
      'ja': '赦す者',
      'ko': '용서자',
      'th': 'ผู้ให้อภัย',
    },

    {
      'ar': 'فصلت',
      'tr': 'Fussilet',
      'en': 'Explained in Detail',
      'ur': 'فصلت',
      'fa': 'فصلت',
      'id': 'Fussilat',
      'ms': 'Fussilat',
      'bn': 'ফুসসিলাত',
      'fr': 'Les Versets détaillés',
      'hi': 'फुस्सिलत',
      'uz': 'Tafsilot berilgan',
      'ru': 'Разъяснены',
      'es': 'Explicado en detalle',
      'pt': 'Explicado em detalhe',
      'de': 'Ausführlich erklärt',
      'it': 'Spiegato in dettaglio',
      'zh': '详细阐明',
      'sw': 'Imefafanuliwa',
      'ja': '詳細に説明されたもの',
      'ko': '상세히 설명된',
      'th': 'อธิบายโดยละเอียด',
    },
    {
      'ar': 'الشورى',
      'tr': 'Şûrâ',
      'en': 'The Consultation',
      'ur': 'الشورى',
      'fa': 'شوری',
      'id': 'Asy-Syura',
      'ms': 'Asy-Syura',
      'bn': 'শুরা',
      'fr': 'La Consultation',
      'hi': 'शूरा',
      'uz': 'Maslahat',
      'ru': 'Совет',
      'es': 'La Consulta',
      'pt': 'A Consulta',
      'de': 'Die Beratung',
      'it': 'La Consultazione',
      'zh': '协商',
      'sw': 'Mashauriano',
      'ja': '協議',
      'ko': '협의',
      'th': 'การปรึกษาหารือ',
    },
    {
      'ar': 'الزخرف',
      'tr': 'Zuhruf',
      'en': 'Ornaments of Gold',
      'ur': 'الزخرف',
      'fa': 'زخرف',
      'id': 'Az-Zukhruf',
      'ms': 'Az-Zukhruf',
      'bn': 'যুখরুফ',
      'fr': 'Les Ornements d’or',
      'hi': 'ज़ुख़रुफ़',
      'uz': 'Zinatchilik',
      'ru': 'Украшения',
      'es': 'Los Adornos',
      'pt': 'Os Adornos',
      'de': 'Die Verzierungen',
      'it': 'Gli Ornamenti',
      'zh': '金饰',
      'sw': 'Mapambo',
      'ja': '装飾',
      'ko': '장식',
      'th': 'เครื่องประดับทอง',
    },
    {
      'ar': 'الدخان',
      'tr': 'Duhân',
      'en': 'The Smoke',
      'ur': 'الدخان',
      'fa': 'دخان',
      'id': 'Ad-Dukhan',
      'ms': 'Ad-Dukhan',
      'bn': 'দুখান',
      'fr': 'La Fumée',
      'hi': 'धुआँ',
      'uz': 'Tuman',
      'ru': 'Дым',
      'es': 'El Humo',
      'pt': 'A Fumaça',
      'de': 'Der Rauch',
      'it': 'Il Fumo',
      'zh': '烟雾',
      'sw': 'Moshi',
      'ja': '煙',
      'ko': '연기',
      'th': 'ควัน',
    },
    {
      'ar': 'الجاثية',
      'tr': 'Câsiye',
      'en': 'The Kneeling',
      'ur': 'الجاثية',
      'fa': 'جاثیه',
      'id': 'Al-Jathiyah',
      'ms': 'Al-Jathiyah',
      'bn': 'জাসিয়াহ',
      'fr': 'Les Agenouillés',
      'hi': 'जासिया',
      'uz': 'Tiz choʻkkanlar',
      'ru': 'Коленопреклонённые',
      'es': 'Los que se arrodillan',
      'pt': 'Os que se ajoelham',
      'de': 'Die Knienden',
      'it': 'I inginocchiati',
      'zh': '跪着的人们',
      'sw': 'Wapigao magoti',
      'ja': 'ひざまずく者たち',
      'ko': '무릎꿇은 자들',
      'th': 'ผู้คุกเข่า',
    },
    {
      'ar': 'الأحقاف',
      'tr': 'Ahkâf',
      'en': 'The Dunes',
      'ur': 'الأحقاف',
      'fa': 'احقاف',
      'id': 'Al-Ahqaf',
      'ms': 'Al-Ahqaf',
      'bn': 'আহকাফ',
      'fr': 'Les Dunes',
      'hi': 'अहक़ाफ़',
      'uz': 'Qumtepalar',
      'ru': 'Песчаные холмы',
      'es': 'Las Dunas',
      'pt': 'As Dunas',
      'de': 'Die Dünen',
      'it': 'Le Dune',
      'zh': '沙丘',
      'sw': 'Vilima vya mchanga',
      'ja': '砂丘',
      'ko': '모래언덕들',
      'th': 'เนินทราย',
    },
    {
      'ar': 'محمد',
      'tr': 'Muhammed',
      'en': 'Muhammad',
      'ur': 'محمد',
      'fa': 'محمد',
      'id': 'Muhammad',
      'ms': 'Muhammad',
      'bn': 'মুহাম্মাদ',
      'fr': 'Muhammad',
      'hi': 'मुहम्मद',
      'uz': 'Muhammad',
      'ru': 'Мухаммад',
      'es': 'Muhammad',
      'pt': 'Muhammad',
      'de': 'Muhammad',
      'it': 'Muhammad',
      'zh': '穆罕默德',
      'sw': 'Muhammad',
      'ja': 'ムハンマド',
      'ko': '무함마드',
      'th': 'มูฮัมหมัด',
    },
    {
      'ar': 'الفتح',
      'tr': 'Fetih',
      'en': 'The Victory',
      'ur': 'الفتح',
      'fa': 'فتح',
      'id': 'Al-Fath',
      'ms': 'Al-Fath',
      'bn': 'ফাতহ',
      'fr': 'La Victoire',
      'hi': 'फतह',
      'uz': 'Gʻalaba',
      'ru': 'Победа',
      'es': 'La Victoria',
      'pt': 'A Vitória',
      'de': 'Der Sieg',
      'it': 'La Vittoria',
      'zh': '胜利',
      'sw': 'Ushindi',
      'ja': '勝利',
      'ko': '승리',
      'th': 'ชัยชนะ',
    },
    {
      'ar': 'الحجرات',
      'tr': 'Hucurât',
      'en': 'The Rooms',
      'ur': 'الحجرات',
      'fa': 'حجرات',
      'id': 'Al-Hujurat',
      'ms': 'Al-Hujurat',
      'bn': 'হুজুরাত',
      'fr': 'Les Chambres',
      'hi': 'हुजुरात',
      'uz': 'Xonalar',
      'ru': 'Комнаты',
      'es': 'Las Habitaciones',
      'pt': 'Os Quartos',
      'de': 'Die Gemächer',
      'it': 'Le Stanze',
      'zh': '房间',
      'sw': 'Vyumba',
      'ja': '部屋',
      'ko': '방들',
      'th': 'ห้องต่างๆ',
    },
    {
      'ar': 'ق',
      'tr': 'Kâf',
      'en': 'Qaf',
      'ur': 'ق',
      'fa': 'ق',
      'id': 'Qaf',
      'ms': 'Qaf',
      'bn': 'কাফ',
      'fr': 'Qaf',
      'hi': 'क़ाफ़',
      'uz': 'Qof',
      'ru': 'Каф',
      'es': 'Qaf',
      'pt': 'Qaf',
      'de': 'Qaf',
      'it': 'Qaf',
      'zh': '卡夫',
      'sw': 'Qaf',
      'ja': 'カーフ',
      'ko': '카프',
      'th': 'กอฟ',
    },
    {
      'ar': 'الذاريات',
      'tr': 'Zâriyât',
      'en': 'The Winnowing Winds',
      'ur': 'الذاريات',
      'fa': 'ذاریات',
      'id': 'Adh-Dhariyat',
      'ms': 'Adh-Dhariyat',
      'bn': 'যারিয়াত',
      'fr': 'Les Vents disséminateurs',
      'hi': 'धारियात',
      'uz': 'Shamollar',
      'ru': 'Развевающие ветры',
      'es': 'Los Vientos que dispersan',
      'pt': 'Os Ventos que espalham',
      'de': 'Die Winde',
      'it': 'I Venti',
      'zh': '播散之风',
      'sw': 'Upepo',
      'ja': '吹き散らす風',
      'ko': '흩뿌리는 바람',
      'th': 'สายลมที่พัดกระจาย',
    },
    {
      'ar': 'الطور',
      'tr': 'Tûr',
      'en': 'The Mount',
      'ur': 'الطور',
      'fa': 'طور',
      'id': 'At-Tur',
      'ms': 'At-Tur',
      'bn': 'তূর',
      'fr': 'Le Mont',
      'hi': 'तूर',
      'uz': 'Togʻ',
      'ru': 'Гора',
      'es': 'El Monte',
      'pt': 'O Monte',
      'de': 'Der Berg',
      'it': 'Il Monte',
      'zh': '山',
      'sw': 'Mlima',
      'ja': '山',
      'ko': '산',
      'th': 'ภูเขา',
    },
    {
      'ar': 'النجم',
      'tr': 'Necm',
      'en': 'The Star',
      'ur': 'النجم',
      'fa': 'نجم',
      'id': 'An-Najm',
      'ms': 'An-Najm',
      'bn': 'নাজম',
      'fr': 'L’Étoile',
      'hi': 'नज्म',
      'uz': 'Yulduz',
      'ru': 'Звезда',
      'es': 'La Estrella',
      'pt': 'A Estrela',
      'de': 'Der Stern',
      'it': 'La Stella',
      'zh': '星星',
      'sw': 'Nyota',
      'ja': '星',
      'ko': '별',
      'th': 'ดาว',
    },
    {
      'ar': 'القمر',
      'tr': 'Kamer',
      'en': 'The Moon',
      'ur': 'القمر',
      'fa': 'قمر',
      'id': 'Al-Qamar',
      'ms': 'Al-Qamar',
      'bn': 'কামার',
      'fr': 'La Lune',
      'hi': 'क़मर',
      'uz': 'Oy',
      'ru': 'Луна',
      'es': 'La Luna',
      'pt': 'A Lua',
      'de': 'Der Mond',
      'it': 'La Luna',
      'zh': '月亮',
      'sw': 'Mwezi',
      'ja': '月',
      'ko': '달',
      'th': 'พระจันทร์',
    },
    {
      'ar': 'الرحمن',
      'tr': 'Rahmân',
      'en': 'The Most Merciful',
      'ur': 'الرحمن',
      'fa': 'رحمن',
      'id': 'Ar-Rahman',
      'ms': 'Ar-Rahman',
      'bn': 'রহমান',
      'fr': 'Le Très Miséricordieux',
      'hi': 'रहमान',
      'uz': 'Rahmon',
      'ru': 'Милостивейший',
      'es': 'El Misericordioso',
      'pt': 'O Misericordioso',
      'de': 'Der Barmherzige',
      'it': 'Il Misericordioso',
      'zh': '至仁主',
      'sw': 'Mwenye Rehema',
      'ja': '慈悲深き者',
      'ko': '자비로우신 분',
      'th': 'ผู้เปี่ยมด้วยความเมตตา',
    },
    {
      'ar': 'الواقعة',
      'tr': 'Vâkıa',
      'en': 'The Inevitable',
      'ur': 'الواقعة',
      'fa': 'واقعه',
      'id': 'Al-Waqi\'ah',
      'ms': 'Al-Waqi\'ah',
      'bn': 'ওয়াকিআহ',
      'fr': 'L’Inevitable',
      'hi': 'वाक़िआह',
      'uz': 'Boʻlishi muqarrar',
      'ru': 'Неизбежное',
      'es': 'Lo Inevitable',
      'pt': 'O Inevitável',
      'de': 'Das Unvermeidliche',
      'it': 'L’Inevitabile',
      'zh': '必然事件',
      'sw': 'Isiyoweza kuepukwa',
      'ja': '避けられぬもの',
      'ko': '피할 수 없는 것',
      'th': 'สิ่งที่หลีกเลี่ยงไม่ได้',
    },
    {
      'ar': 'الحديد',
      'tr': 'Hadîd',
      'en': 'The Iron',
      'ur': 'الحديد',
      'fa': 'حدید',
      'id': 'Al-Hadid',
      'ms': 'Al-Hadid',
      'bn': 'হাদিদ',
      'fr': 'Le Fer',
      'hi': 'हदीद',
      'uz': 'Temir',
      'ru': 'Железо',
      'es': 'El Hierro',
      'pt': 'O Ferro',
      'de': 'Das Eisen',
      'it': 'Il Ferro',
      'zh': '铁',
      'sw': 'Chuma',
      'ja': '鉄',
      'ko': '철',
      'th': 'เหล็ก',
    },
    {
      'ar': 'المجادلة',
      'tr': 'Mücâdele',
      'en': 'The Pleading Woman',
      'ur': 'المجادلة',
      'fa': 'مجادله',
      'id': 'Al-Mujadilah',
      'ms': 'Al-Mujadilah',
      'bn': 'মুজাদালাহ',
      'fr': 'La Plaideuse',
      'hi': 'मुझादिला',
      'uz': 'Tortishuvchi ayol',
      'ru': 'Препирающаяся',
      'es': 'La Mujer que discute',
      'pt': 'A Mulher que discute',
      'de': 'Die Streitende',
      'it': 'La Donna che discute',
      'zh': '争辩的女人',
      'sw': 'Mwanamke anayebishana',
      'ja': '論じる女',
      'ko': '논쟁하는 여자',
      'th': 'หญิงที่โต้เถียง',
    },
    {
      'ar': 'الحشر',
      'tr': 'Haşr',
      'en': 'The Gathering',
      'ur': 'الحشر',
      'fa': 'حشر',
      'id': 'Al-Hashr',
      'ms': 'Al-Hashr',
      'bn': 'হাশর',
      'fr': 'Le Rassemblement',
      'hi': 'हश्र',
      'uz': 'Toʻplanish',
      'ru': 'Собрание',
      'es': 'La Reunión',
      'pt': 'A Reunião',
      'de': 'Die Versammlung',
      'it': 'Il Raduno',
      'zh': '聚集',
      'sw': 'Mkusanyiko',
      'ja': '集まり',
      'ko': '모임',
      'th': 'การรวมตัว',
    },
    {
      'ar': 'الممتحنة',
      'tr': 'Mümtehine',
      'en': 'The Woman Tested',
      'ur': 'الممتحنة',
      'fa': 'ممتحنه',
      'id': 'Al-Mumtahanah',
      'ms': 'Al-Mumtahanah',
      'bn': 'মুমতাহানাহ',
      'fr': 'L’Éprouvée',
      'hi': 'मुमतहना',
      'uz': 'Sinovdan oʻtgan ayol',
      'ru': 'Испытуемая женщина',
      'es': 'La Mujer Probada',
      'pt': 'A Mulher Provada',
      'de': 'Die Geprüfte',
      'it': 'La Donna messa alla prova',
      'zh': '受考验的女人',
      'sw': 'Mwanamke aliyejaribiwa',
      'ja': '試された女',
      'ko': '시험받은 여자',
      'th': 'หญิงที่ถูกทดสอบ',
    },

    {
      'ar': 'الصف',
      'tr': 'Saff',
      'en': 'As-Saff',
      'id': 'As-Saff',
      'ur': 'الصف',
      'ms': 'As-Saff',
      'bn': 'আস-সাফ',
      'fr': 'Les Rangées',
      'hi': 'सफ़',
      'fa': 'صف',
      'uz': 'Saff',
      'ru': 'Ас-Сафф',
      'es': 'La Fila',
      'pt': 'As-Saff',
      'de': 'Die Reihe',
      'it': 'Le Schiere',
      'zh': '排队',
      'sw': 'Safu',
      'ja': '行列',
      'ko': '행렬',
      'th': 'แถว',
    },
    {
      'ar': 'الجمعة',
      'tr': 'Cum\'a',
      'en': 'Al-Jumu\'ah',
      'id': 'Al-Jumuah',
      'ur': 'الجمعة',
      'ms': 'Al-Jumuah',
      'bn': 'জুম্মা',
      'fr': 'Le Vendredi',
      'hi': 'जुम्मा',
      'fa': 'جمعه',
      'uz': 'Jum\'a',
      'ru': 'Аль-Джума',
      'es': 'El Viernes',
      'pt': 'Al-Jumuah',
      'de': 'Al-Jumuah',
      'it': 'Al-Jumuah',
      'zh': '聚礼',
      'sw': 'Ijumaa',
      'ja': '金曜日',
      'ko': '알주무아',
      'th': 'วันศุกร์',
    },
    {
      'ar': 'المنافقون',
      'tr': 'Münâfikûn',
      'en': 'Al-Munafiqun',
      'id': 'Al-Munafiqun',
      'ur': 'المنافقون',
      'ms': 'Al-Munafiqun',
      'bn': 'মুনাফিকুন',
      'fr': 'Les Hypocrites',
      'hi': 'मुनाफ़िकून',
      'fa': 'منافقون',
      'uz': 'Munafiqun',
      'ru': 'Аль-Мунавфикун',
      'es': 'Los Hipócritas',
      'pt': 'Al-Munafiqun',
      'de': 'Die Heuchler',
      'it': 'I Munafiqun',
      'zh': '伪君子',
      'sw': 'Wapumbavu',
      'ja': '偽善者',
      'ko': '무나피쿤',
      'th': 'พวกขี้ขลาด',
    },
    {
      'ar': 'التغابن',
      'tr': 'Teğâbün',
      'en': 'At-Taghabun',
      'id': 'At-Taghabun',
      'ur': 'التغابن',
      'ms': 'At-Taghabun',
      'bn': 'আত-তাগাবুন',
      'fr': 'La Perte et le Gain',
      'hi': 'अत-तग़ाबुन',
      'fa': 'التغابن',
      'uz': 'At-Taghabun',
      'ru': 'Ат-Тагхабун',
      'es': 'La Pérdida y la Ganancia',
      'pt': 'At-Taghabun',
      'de': 'Der Verlust',
      'it': 'At-Taghabun',
      'zh': '失与得',
      'sw': 'At-Taghabun',
      'ja': 'アッ＝タガーブン',
      'ko': '아트-타가붕',
      'th': 'การสูญเสียและได้กำไร',
    },
    {
      'ar': 'الطلاق',
      'tr': 'Talâk',
      'en': 'At-Talaq',
      'id': 'At-Talaq',
      'ur': 'الطلاق',
      'ms': 'At-Talaq',
      'bn': 'আত-তালাক',
      'fr': 'Le Divorce',
      'hi': 'अत-तलाक',
      'fa': 'طلاق',
      'uz': 'At-Talaq',
      'ru': 'Ат-Талак',
      'es': 'El Divorcio',
      'pt': 'At-Talaq',
      'de': 'Die Scheidung',
      'it': 'At-Talaq',
      'zh': '离婚',
      'sw': 'Talak',
      'ja': 'アッ＝タラーク',
      'ko': '아트-탈락',
      'th': 'การหย่า',
    },
    {
      'ar': 'التحريم',
      'tr': 'Tahrîm',
      'en': 'At-Tahrim',
      'id': 'At-Tahrim',
      'ur': 'التحريم',
      'ms': 'At-Tahrim',
      'bn': 'আত-তাহরিম',
      'fr': 'L’Interdiction',
      'hi': 'अत-तहरीम',
      'fa': 'تحریم',
      'uz': 'At-Tahrim',
      'ru': 'Ат-Тахрим',
      'es': 'La Prohibición',
      'pt': 'At-Tahrim',
      'de': 'Das Verbot',
      'it': 'At-Tahrim',
      'zh': '禁止',
      'sw': 'At-Tahrim',
      'ja': 'アッ＝タフリーム',
      'ko': '아트-타흐림',
      'th': 'การห้าม',
    },
    {
      'ar': 'الملك',
      'tr': 'Mülk',
      'en': 'Al-Mulk',
      'id': 'Al-Mulk',
      'ur': 'الملك',
      'ms': 'Al-Mulk',
      'bn': 'আল-মুলক',
      'fr': 'La Royauté',
      'hi': 'अल-मुल्क',
      'fa': 'ملک',
      'uz': 'Al-Mulk',
      'ru': 'Аль-Мулк',
      'es': 'La Soberanía',
      'pt': 'Al-Mulk',
      'de': 'Die Herrschaft',
      'it': 'Al-Mulk',
      'zh': '王权',
      'sw': 'Al-Mulk',
      'ja': 'アル＝ムルク',
      'ko': '알-물크',
      'th': 'อำนาจของพระเจ้า',
    },
    {
      'ar': 'القلم',
      'tr': 'Kalem',
      'en': 'Al-Qalam',
      'id': 'Al-Qalam',
      'ur': 'القلم',
      'ms': 'Al-Qalam',
      'bn': 'আল-ক্বালেম',
      'fr': 'Le Calame',
      'hi': 'अल-क़लम',
      'fa': 'قلم',
      'uz': 'Al-Qalam',
      'ru': 'Аль-Калам',
      'es': 'El Calamo',
      'pt': 'Al-Qalam',
      'de': 'Die Feder',
      'it': 'Al-Qalam',
      'zh': '笔',
      'sw': 'Al-Qalam',
      'ja': 'アル＝カラム',
      'ko': '알-칼렘',
      'th': 'ปากกา',
    },
    {
      'ar': 'الحاقة',
      'tr': 'Hâkka',
      'en': 'Al-Haqqah',
      'id': 'Al-Haqqah',
      'ur': 'الحاقة',
      'ms': 'Al-Haqqah',
      'bn': 'আল-হাক্কাহ',
      'fr': 'La Réalité',
      'hi': 'अल-हक्का',
      'fa': 'الحاقه',
      'uz': 'Al-Haqqah',
      'ru': 'Аль-Хакка',
      'es': 'La Realidad',
      'pt': 'Al-Haqqah',
      'de': 'Die Wahrheit',
      'it': 'Al-Haqqah',
      'zh': '现实',
      'sw': 'Al-Haqqah',
      'ja': 'アル＝ハッカ',
      'ko': '알-핫카',
      'th': 'ความจริง',
    },
    {
      'ar': 'المعارج',
      'tr': 'Meâric',
      'en': 'Al-Ma\'arij',
      'id': 'Al-Ma\'arij',
      'ur': 'المعارج',
      'ms': 'Al-Ma\'arij',
      'bn': 'আল-মাআরিজ',
      'fr': 'Les Voies d’Ascension',
      'hi': 'अल-मआरिज़',
      'fa': 'المعارج',
      'uz': 'Al-Maarij',
      'ru': 'Аль-Маариф',
      'es': 'Las Escaleras',
      'pt': 'Al-Maarij',
      'de': 'Die Aufstiege',
      'it': 'Al-Ma\'arij',
      'zh': '阶梯',
      'sw': 'Al-Ma\'arij',
      'ja': 'アル＝マーリジュ',
      'ko': '알-마아리즈',
      'th': 'บันไดสู่สวรรค์',
    },

    {
      'ar': 'نوح',
      'tr': 'Nûh',
      'en': 'Nuh',
      'id': 'Nuh',
      'ur': 'نوح',
      'ms': 'Nuh',
      'bn': 'নূহ',
      'fr': 'Noé',
      'hi': 'नूह',
      'fa': 'نوح',
      'uz': 'Nuh',
      'ru': 'Нух',
      'es': 'Noé',
      'pt': 'Nuh',
      'de': 'Nuh',
      'it': 'Noè',
      'zh': '努哈',
      'sw': 'Nuh',
      'ja': 'ノア',
      'ko': '누흐',
      'th': 'นูห์',
    },
    {
      'ar': 'الجن',
      'tr': 'Cin',
      'en': 'Al-Jinn',
      'id': 'Al-Jinn',
      'ur': 'الجن',
      'ms': 'Al-Jinn',
      'bn': 'আল-জিন্ন',
      'fr': 'Les Djinns',
      'hi': 'अल-जिन्न',
      'fa': 'جن',
      'uz': 'Al-Jinn',
      'ru': 'Аль-Джинн',
      'es': 'Los Genios',
      'pt': 'Al-Jinn',
      'de': 'Die Dschinn',
      'it': 'Gli Jinn',
      'zh': '精灵',
      'sw': 'Al-Jinn',
      'ja': 'アル＝ジン',
      'ko': '알-진',
      'th': 'จินน์',
    },
    {
      'ar': 'المزمل',
      'tr': 'Müzzemmil',
      'en': 'Al-Muzzammil',
      'id': 'Al-Muzzammil',
      'ur': 'المزمل',
      'ms': 'Al-Muzzammil',
      'bn': 'আল-মুজ্জাম্মিল',
      'fr': 'L’Enveloppé',
      'hi': 'अल-मुज्ज़म्मिल',
      'fa': 'المزمل',
      'uz': 'Al-Muzzammil',
      'ru': 'Аль-Муззаммиль',
      'es': 'El Envuelto',
      'pt': 'Al-Muzzammil',
      'de': 'Der Eingehüllte',
      'it': 'Al-Muzzammil',
      'zh': '裹着的人',
      'sw': 'Al-Muzzammil',
      'ja': 'アル＝ムザンミル',
      'ko': '알-무잠밀',
      'th': 'ผู้ห่อหุ้ม',
    },
    {
      'ar': 'المدثر',
      'tr': 'Müddessir',
      'en': 'Al-Muddaththir',
      'id': 'Al-Muddaththir',
      'ur': 'المدثر',
      'ms': 'Al-Muddaththir',
      'bn': 'আল-মুদ্দসির',
      'fr': 'Le Revêtu d’un Manteau',
      'hi': 'अल-मुद्दश्शिर',
      'fa': 'المدثر',
      'uz': 'Al-Muddaththir',
      'ru': 'Аль-Муддассир',
      'es': 'El Envuelto en un Manto',
      'pt': 'Al-Muddaththir',
      'de': 'Der Bedeckte',
      'it': 'Al-Muddaththir',
      'zh': '裹着披风者',
      'sw': 'Al-Muddaththir',
      'ja': 'アル＝ムッダッスィル',
      'ko': '알-무다쓰시르',
      'th': 'ผู้สวมผ้าคลุม',
    },
    {
      'ar': 'القيامة',
      'tr': 'Kıyâme',
      'en': 'Al-Qiyamah',
      'id': 'Al-Qiyamah',
      'ur': 'القيامة',
      'ms': 'Al-Qiyamah',
      'bn': 'আল-কিয়ামাহ',
      'fr': 'La Résurrection',
      'hi': 'अल-कियामह',
      'fa': 'قیامت',
      'uz': 'Al-Qiyamah',
      'ru': 'Аль-Кийама',
      'es': 'La Resurrección',
      'pt': 'Al-Qiyamah',
      'de': 'Die Auferstehung',
      'it': 'Al-Qiyamah',
      'zh': '复活',
      'sw': 'Al-Qiyamah',
      'ja': 'アル＝キヤーマ',
      'ko': '알-키야마',
      'th': 'วันบัญชีผลกรรม',
    },
    {
      'ar': 'الإنسان',
      'tr': 'İnsân',
      'en': 'Al-Insan',
      'id': 'Al-Insan',
      'ur': 'الإنسان',
      'ms': 'Al-Insan',
      'bn': 'আল-ইনসান',
      'fr': 'L’Homme',
      'hi': 'अल-इंसान',
      'fa': 'انسان',
      'uz': 'Al-Insan',
      'ru': 'Аль-Инсан',
      'es': 'El Hombre',
      'pt': 'Al-Insan',
      'de': 'Der Mensch',
      'it': 'Al-Insan',
      'zh': '人',
      'sw': 'Al-Insan',
      'ja': 'アル＝インサーン',
      'ko': '알-인산',
      'th': 'มนุษย์',
    },
    {
      'ar': 'المرسلات',
      'tr': 'Mürselât',
      'en': 'Al-Mursalat',
      'id': 'Al-Mursalat',
      'ur': 'المرسلات',
      'ms': 'Al-Mursalat',
      'bn': 'আল-মুরসালাত',
      'fr': 'Les Envoyées',
      'hi': 'अल-मुर्सलात',
      'fa': 'مرسلات',
      'uz': 'Al-Mursalat',
      'ru': 'Аль-Мурсалат',
      'es': 'Las Enviadas',
      'pt': 'Al-Mursalat',
      'de': 'Die Gesandten',
      'it': 'Al-Mursalat',
      'zh': '使者',
      'sw': 'Al-Mursalat',
      'ja': 'アル＝ムルサラート',
      'ko': '알-무르살라트',
      'th': 'ผู้ส่งสาร',
    },
    {
      'ar': 'النبأ',
      'tr': 'Nebe',
      'en': 'An-Naba',
      'id': 'An-Naba',
      'ur': 'النبأ',
      'ms': 'An-Naba',
      'bn': 'আন-নাবা',
      'fr': 'La Nouvelle',
      'hi': 'अन-नबा',
      'fa': 'خبر',
      'uz': 'An-Naba',
      'ru': 'Ан-Наба',
      'es': 'La Noticia',
      'pt': 'An-Naba',
      'de': 'Die Nachricht',
      'it': 'An-Naba',
      'zh': '消息',
      'sw': 'An-Naba',
      'ja': 'アン＝ナバ',
      'ko': '안-나바',
      'th': 'ข่าวใหญ่',
    },
    {
      'ar': 'النازعات',
      'tr': 'Nâziât',
      'en': 'An-Nazi\'at',
      'id': 'An-Naziat',
      'ur': 'النازعات',
      'ms': 'An-Naziat',
      'bn': 'আন-নাজিয়াত',
      'fr': 'Les Arrachantes',
      'hi': 'अन-नाज़िआत',
      'fa': 'نازعات',
      'uz': 'An-Naziat',
      'ru': 'Ан-Нази\'ат',
      'es': 'Las Arrancadoras',
      'pt': 'An-Naziat',
      'de': 'Die Herausreißenden',
      'it': 'An-Naziat',
      'zh': '拔起者',
      'sw': 'An-Naziat',
      'ja': 'アン＝ナジアート',
      'ko': '안-나지앗',
      'th': 'ผู้ดึงออก',
    },
    {
      'ar': 'عبس',
      'tr': 'Abese',
      'en': 'Abasa',
      'id': 'Abasa',
      'ur': 'عبس',
      'ms': 'Abasa',
      'bn': 'আবসা',
      'fr': 'Il S’est Renfrogné',
      'hi': 'अबसा',
      'fa': 'عبس',
      'uz': 'Abasa',
      'ru': 'Абаса',
      'es': 'Se Frunció',
      'pt': 'Abasa',
      'de': 'Er runzelte die Stirn',
      'it': 'Abasa',
      'zh': '他皱眉',
      'sw': 'Abasa',
      'ja': 'アバサ',
      'ko': '아바사',
      'th': 'เขาบึ้งตา',
    },

    {
      'ar': 'التكوير',
      'tr': 'Tekvîr',
      'en': 'At-Takwir',
      'id': 'At-Takwir',
      'ur': 'At-Takwir',
      'ms': 'At-Takwir',
      'bn': 'আত-তাকউইর',
      'fr': 'At-Takwir',
      'hi': 'अत-तकवीर',
      'fa': 'التکویر',
      'uz': 'At-Takvir',
      'ru': 'Ат-Таквир',
      'es': 'At-Takwir',
      'pt': 'At-Takwir',
      'de': 'At-Takwir',
      'it': 'At-Takwir',
      'zh': 'At-Takwir',
      'sw': 'At-Takwir',
      'ja': 'アッ＝タクウィール',
      'ko': '아트-타크위르',
      'th': 'อัต-ตักวีร์',
    },

    {
      'ar': 'الانفطار',
      'tr': 'İnfitâr',
      'en': 'Al-Infitar',
      'id': 'Al-Infitar',
      'ur': 'Al-Infitar',
      'ms': 'Al-Infitar',
      'bn': 'আল-ইনফিতার',
      'fr': 'Al-Infitar',
      'hi': 'अल-इन्फितार',
      'fa': 'الانفطار',
      'uz': 'Al-Infitar',
      'ru': 'Аль-Инфитар',
      'es': 'Al-Infitar',
      'pt': 'Al-Infitar',
      'de': 'Al-Infitar',
      'it': 'Al-Infitar',
      'zh': 'Al-Infitar',
      'sw': 'Al-Infitar',
      'ja': 'アル＝インフィター',
      'ko': '알-인피타르',
      'th': 'อัล-อินฟิทาร์',
    },

    {
      'ar': 'المطففين',
      'tr': 'Mutaffifîn',
      'en': 'Al-Mutaffifin',
      'id': 'Al-Mutaffifin',
      'ur': 'Al-Mutaffifin',
      'ms': 'Al-Mutaffifin',
      'bn': 'আল-মুতাফফিফীন',
      'fr': 'Al-Mutaffifin',
      'hi': 'अल-मुताफ़्फ़िफ़ीन',
      'fa': 'المطففين',
      'uz': 'Al-Mutaffifin',
      'ru': 'Аль-Мутаффифин',
      'es': 'Al-Mutaffifin',
      'pt': 'Al-Mutaffifin',
      'de': 'Al-Mutaffifin',
      'it': 'Al-Mutaffifin',
      'zh': 'Al-Mutaffifin',
      'sw': 'Al-Mutaffifin',
      'ja': 'アル＝ムタッフィフィーン',
      'ko': '알-무타피핀',
      'th': 'อัล-มุตัฟฟีฟีน',
    },

    {
      'ar': 'الانشقاق',
      'tr': 'İnşikâk',
      'en': 'Al-Inshiqaq',
      'id': 'Al-Inshiqaq',
      'ur': 'Al-Inshiqaq',
      'ms': 'Al-Inshiqaq',
      'bn': 'আল-ইনশিকাক',
      'fr': 'Al-Inshiqaq',
      'hi': 'अल-इंशिक़ाक़',
      'fa': 'الانشقاق',
      'uz': 'Al-Inshiqaq',
      'ru': 'Аль-Иншикак',
      'es': 'Al-Inshiqaq',
      'pt': 'Al-Inshiqaq',
      'de': 'Al-Inshiqaq',
      'it': 'Al-Inshiqaq',
      'zh': 'Al-Inshiqaq',
      'sw': 'Al-Inshiqaq',
      'ja': 'アル＝インシカーク',
      'ko': '알-인시키악',
      'th': 'อัล-อินชิกัก',
    },

    {
      'ar': 'البروج',
      'tr': 'Burûj',
      'en': 'Al-Buruj',
      'id': 'Al-Buruj',
      'ur': 'Al-Buruj',
      'ms': 'Al-Buruj',
      'bn': 'আল-বুরুজ',
      'fr': 'Al-Buruj',
      'hi': 'अल-बुरूज',
      'fa': 'البروج',
      'uz': 'Al-Buruj',
      'ru': 'Аль-Бурудж',
      'es': 'Al-Buruj',
      'pt': 'Al-Buruj',
      'de': 'Al-Buruj',
      'it': 'Al-Buruj',
      'zh': 'Al-Buruj',
      'sw': 'Al-Buruj',
      'ja': 'アル＝ブルージュ',
      'ko': '알-부루즈',
      'th': 'อัล-บูรุต',
    },

    {
      'ar': 'الطارق',
      'tr': 'Târık',
      'en': 'At-Tariq',
      'id': 'At-Tariq',
      'ur': 'At-Tariq',
      'ms': 'At-Tariq',
      'bn': 'আত-তারিক',
      'fr': 'At-Tariq',
      'hi': 'अत-तारीक़',
      'fa': 'الطارق',
      'uz': 'At-Tariq',
      'ru': 'Ат-Тарик',
      'es': 'At-Tariq',
      'pt': 'At-Tariq',
      'de': 'At-Tariq',
      'it': 'At-Tariq',
      'zh': 'At-Tariq',
      'sw': 'At-Tariq',
      'ja': 'アッ＝タリーク',
      'ko': '아트-타리크',
      'th': 'อัต-ตาริก',
    },

    {
      'ar': 'الأعلى',
      'tr': 'A\'lâ',
      'en': 'Al-A\'la',
      'id': 'Al-A\'la',
      'ur': 'Al-A\'la',
      'ms': 'Al-A\'la',
      'bn': 'আল-আল্যা',
      'fr': 'Al-A\'la',
      'hi': 'अल-अला',
      'fa': 'الأعلى',
      'uz': 'Al-A\'la',
      'ru': 'Аль-Аля',
      'es': 'Al-A\'la',
      'pt': 'Al-A\'la',
      'de': 'Al-A\'la',
      'it': 'Al-A\'la',
      'zh': 'Al-A\'la',
      'sw': 'Al-A\'la',
      'ja': 'アル＝アーラ',
      'ko': '알-알라',
      'th': 'อัล-อาลา',
    },

    {
      'ar': 'الغاشية',
      'tr': 'Ğâşiye',
      'en': 'Al-Ghashiyah',
      'id': 'Al-Ghashiyah',
      'ur': 'Al-Ghashiyah',
      'ms': 'Al-Ghashiyah',
      'bn': 'আল-ঘাশিয়াহ',
      'fr': 'Al-Ghashiyah',
      'hi': 'अल-घाशियाह',
      'fa': 'الغاشیه',
      'uz': 'Al-Ghashiyah',
      'ru': 'Аль-Гашия',
      'es': 'Al-Ghashiyah',
      'pt': 'Al-Ghashiyah',
      'de': 'Al-Ghashiyah',
      'it': 'Al-Ghashiyah',
      'zh': 'Al-Ghashiyah',
      'sw': 'Al-Ghashiyah',
      'ja': 'アル＝ガーシーヤ',
      'ko': '알-가시야',
      'th': 'อัล-ฆาชียะห์',
    },

    {
      'ar': 'الفجر',
      'tr': 'Fecr',
      'en': 'Al-Fajr',
      'id': 'Al-Fajr',
      'ur': 'Al-Fajr',
      'ms': 'Al-Fajr',
      'bn': 'আল-ফজর',
      'fr': 'Al-Fajr',
      'hi': 'अल-फजर',
      'fa': 'الفجر',
      'uz': 'Al-Fajr',
      'ru': 'Аль-Фаджр',
      'es': 'Al-Fajr',
      'pt': 'Al-Fajr',
      'de': 'Al-Fajr',
      'it': 'Al-Fajr',
      'zh': 'Al-Fajr',
      'sw': 'Al-Fajr',
      'ja': 'アル＝ファジュル',
      'ko': '알-파즈르',
      'th': 'อัล-ฟัจร์',
    },

    {
      'ar': 'البلد',
      'tr': 'Beled',
      'en': 'Al-Balad',
      'id': 'Al-Balad',
      'ur': 'Al-Balad',
      'ms': 'Al-Balad',
      'bn': 'আল-বালাদ',
      'fr': 'Al-Balad',
      'hi': 'अल-बलद',
      'fa': 'البلد',
      'uz': 'Al-Balad',
      'ru': 'Аль-Балад',
      'es': 'Al-Balad',
      'pt': 'Al-Balad',
      'de': 'Al-Balad',
      'it': 'Al-Balad',
      'zh': 'Al-Balad',
      'sw': 'Al-Balad',
      'ja': 'アル＝バラド',
      'ko': '알-발라드',
      'th': 'อัล-บาลัด',
    },

    {
      'ar': 'الشمس',
      'tr': 'Şems',
      'en': 'Ash-Shams',
      'id': 'Ash-Shams',
      'ur': 'Ash-Shams',
      'ms': 'Ash-Shams',
      'bn': 'আশ-শামস',
      'fr': 'Ash-Shams',
      'hi': 'अश-शम्स',
      'fa': 'الشمس',
      'uz': 'Ash-Shams',
      'ru': 'Аш-Шамс',
      'es': 'Ash-Shams',
      'pt': 'Ash-Shams',
      'de': 'Ash-Shams',
      'it': 'Ash-Shams',
      'zh': 'Ash-Shams',
      'sw': 'Ash-Shams',
      'ja': 'アッ＝シャムス',
      'ko': '아시-샴스',
      'th': 'อัช-ชัมส์',
    },

    {
      'ar': 'الليل',
      'tr': 'Leyl',
      'en': 'Al-Layl',
      'id': 'Al-Layl',
      'ur': 'Al-Layl',
      'ms': 'Al-Layl',
      'bn': 'আল-লাইল',
      'fr': 'Al-Layl',
      'hi': 'अल-लै़ल',
      'fa': 'اللیل',
      'uz': 'Al-Layl',
      'ru': 'Аль-Лайль',
      'es': 'Al-Layl',
      'pt': 'Al-Layl',
      'de': 'Al-Layl',
      'it': 'Al-Layl',
      'zh': 'Al-Layl',
      'sw': 'Al-Layl',
      'ja': 'アル＝ライル',
      'ko': '알-라일',
      'th': 'อัล-ลัยล์',
    },

    {
      'ar': 'الضحى',
      'tr': 'Duhâ',
      'en': 'Ad-Dhuha',
      'id': 'Ad-Dhuha',
      'ur': 'Ad-Dhuha',
      'ms': 'Ad-Dhuha',
      'bn': 'আদ-যূহা',
      'fr': 'Ad-Dhuha',
      'hi': 'अद-धुहा',
      'fa': 'الضحی',
      'uz': 'Ad-Dhuha',
      'ru': 'Ад-Духа',
      'es': 'Ad-Dhuha',
      'pt': 'Ad-Dhuha',
      'de': 'Ad-Dhuha',
      'it': 'Ad-Dhuha',
      'zh': 'Ad-Dhuha',
      'sw': 'Ad-Dhuha',
      'ja': 'アッ＝ズフハー',
      'ko': '아드-주하',
      'th': 'อัด-ดูฮา',
    },

    {
      'ar': 'الشرح',
      'tr': 'İnşirâh',
      'en': 'Ash-Sharh',
      'id': 'Ash-Sharh',
      'ur': 'Ash-Sharh',
      'ms': 'Ash-Sharh',
      'bn': 'আশ-শরহ',
      'fr': 'Ash-Sharh',
      'hi': 'अश-शरह',
      'fa': 'الشرح',
      'uz': 'Ash-Sharh',
      'ru': 'Аш-Шарх',
      'es': 'Ash-Sharh',
      'pt': 'Ash-Sharh',
      'de': 'Ash-Sharh',
      'it': 'Ash-Sharh',
      'zh': 'Ash-Sharh',
      'sw': 'Ash-Sharh',
      'ja': 'アッ＝シャルフ',
      'ko': '아쉬-샤르',
      'th': 'อัช-ชัรห์',
    },

    {
      'ar': 'التين',
      'tr': 'Tîn',
      'en': 'At-Tin',
      'id': 'At-Tin',
      'ur': 'At-Tin',
      'ms': 'At-Tin',
      'bn': 'আত-তিন',
      'fr': 'At-Tin',
      'hi': 'अत-तिन',
      'fa': 'التین',
      'uz': 'At-Tin',
      'ru': 'Ат-Тин',
      'es': 'At-Tin',
      'pt': 'At-Tin',
      'de': 'At-Tin',
      'it': 'At-Tin',
      'zh': 'At-Tin',
      'sw': 'At-Tin',
      'ja': 'アッ＝ティーン',
      'ko': '아트-틴',
      'th': 'อัต-ตีน',
    },

    {
      'ar': 'العلق',
      'tr': 'Alak',
      'en': 'Al-Alaq',
      'id': 'Al-Alaq',
      'ur': 'Al-Alaq',
      'ms': 'Al-Alaq',
      'bn': 'আল-আলাক',
      'fr': 'Al-Alaq',
      'hi': 'अल-अलक़',
      'fa': 'العلق',
      'uz': 'Al-Alaq',
      'ru': 'Аль-Алак',
      'es': 'Al-Alaq',
      'pt': 'Al-Alaq',
      'de': 'Al-Alaq',
      'it': 'Al-Alaq',
      'zh': 'Al-Alaq',
      'sw': 'Al-Alaq',
      'ja': 'アル＝アラク',
      'ko': '알-알락',
      'th': 'อัล-อะลาก',
    },

    {
      'ar': 'القدر',
      'tr': 'Kadir',
      'en': 'Al-Qadr',
      'id': 'Al-Qadr',
      'ur': 'Al-Qadr',
      'ms': 'Al-Qadr',
      'bn': 'আল-কদর',
      'fr': 'Al-Qadr',
      'hi': 'अल-क़दर',
      'fa': 'القدر',
      'uz': 'Al-Qadr',
      'ru': 'Аль-Кадр',
      'es': 'Al-Qadr',
      'pt': 'Al-Qadr',
      'de': 'Al-Qadr',
      'it': 'Al-Qadr',
      'zh': 'Al-Qadr',
      'sw': 'Al-Qadr',
      'ja': 'アル＝カドル',
      'ko': '알-카드르',
      'th': 'อัล-กอดรฺ',
    },

    {
      'ar': 'البينة',
      'tr': 'Beyyine',
      'en': 'Al-Bayyinah',
      'id': 'Al-Bayyinah',
      'ur': 'Al-Bayyinah',
      'ms': 'Al-Bayyinah',
      'bn': 'আল-বয়্যিনাহ',
      'fr': 'Al-Bayyinah',
      'hi': 'अल-बैय्यिनाह',
      'fa': 'البینه',
      'uz': 'Al-Bayyinah',
      'ru': 'Аль-Баййина',
      'es': 'Al-Bayyinah',
      'pt': 'Al-Bayyinah',
      'de': 'Al-Bayyinah',
      'it': 'Al-Bayyinah',
      'zh': 'Al-Bayyinah',
      'sw': 'Al-Bayyinah',
      'ja': 'アル＝バイッィナ',
      'ko': '알-바이이나',
      'th': 'อัล-บัยญีนะห์',
    },

    {
      'ar': 'الزلزلة',
      'tr': 'Zilzâl',
      'en': 'Az-Zalzalah',
      'id': 'Az-Zalzalah',
      'ur': 'Az-Zalzalah',
      'ms': 'Az-Zalzalah',
      'bn': 'আয-জালজালাহ',
      'fr': 'Az-Zalzalah',
      'hi': 'अज़-ज़लज़लाह',
      'fa': 'الزلزله',
      'uz': 'Az-Zalzalah',
      'ru': 'Аз-Залзалах',
      'es': 'Az-Zalzalah',
      'pt': 'Az-Zalzalah',
      'de': 'Az-Zalzalah',
      'it': 'Az-Zalzalah',
      'zh': 'Az-Zalzalah',
      'sw': 'Az-Zalzalah',
      'ja': 'アズ＝ザルザラー',
      'ko': '아즈-잘잘라',
      'th': 'อัซ-ซัลซะละฮ์',
    },

    {
      'ar': 'العاديات',
      'tr': 'Âdiyât',
      'en': 'Al-Adiyat',
      'id': 'Al-Adiyat',
      'ur': 'Al-Adiyat',
      'ms': 'Al-Adiyat',
      'bn': 'আল-আদিয়াত',
      'fr': 'Al-Adiyat',
      'hi': 'अल-आदियात',
      'fa': 'العادیات',
      'uz': 'Al-Adiyat',
      'ru': 'Аль-Адият',
      'es': 'Al-Adiyat',
      'pt': 'Al-Adiyat',
      'de': 'Al-Adiyat',
      'it': 'Al-Adiyat',
      'zh': 'Al-Adiyat',
      'sw': 'Al-Adiyat',
      'ja': 'アル＝アディヤート',
      'ko': '알-아디야트',
      'th': 'อัล-อะดียาต',
    },

    {
      'ar': 'القارعة',
      'tr': 'Kâria',
      'en': 'Al-Qari\'ah',
      'id': 'Al-Qari\'ah',
      'ur': 'Al-Qari\'ah',
      'ms': 'Al-Qari\'ah',
      'bn': 'আল-কারিআহ',
      'fr': 'Al-Qari\'ah',
      'hi': 'अल-कारिआह',
      'fa': 'القارعة',
      'uz': 'Al-Qari\'ah',
      'ru': 'Аль-Кари\'ах',
      'es': 'Al-Qari\'ah',
      'pt': 'Al-Qari\'ah',
      'de': 'Al-Qari\'ah',
      'it': 'Al-Qari\'ah',
      'zh': 'Al-Qari\'ah',
      'sw': 'Al-Qari\'ah',
      'ja': 'アル＝カリア',
      'ko': '알-카리아',
      'th': 'อัล-กอเรียะห์',
    },

    {
      'ar': 'التكاثر',
      'tr': 'Tekâsür',
      'en': 'At-Takathur',
      'id': 'At-Takathur',
      'ur': 'At-Takathur',
      'ms': 'At-Takathur',
      'bn': 'আত-তাকাসুর',
      'fr': 'At-Takathur',
      'hi': 'अत-तकासुर',
      'fa': 'التکاثر',
      'uz': 'At-Takathur',
      'ru': 'Ат-Такатхур',
      'es': 'At-Takathur',
      'pt': 'At-Takathur',
      'de': 'At-Takathur',
      'it': 'At-Takathur',
      'zh': 'At-Takathur',
      'sw': 'At-Takathur',
      'ja': 'アッ＝タカスール',
      'ko': '아트-타카스르',
      'th': 'อัต-ตะกะซุร',
    },

    {
      'ar': 'العصر',
      'tr': 'Asr',
      'en': 'Al-Asr',
      'id': 'Al-Asr',
      'ur': 'Al-Asr',
      'ms': 'Al-Asr',
      'bn': 'আল-আসর',
      'fr': 'Al-Asr',
      'hi': 'अल-असर',
      'fa': 'العصر',
      'uz': 'Al-Asr',
      'ru': 'Аль-Аср',
      'es': 'Al-Asr',
      'pt': 'Al-Asr',
      'de': 'Al-Asr',
      'it': 'Al-Asr',
      'zh': 'Al-Asr',
      'sw': 'Al-Asr',
      'ja': 'アル＝アスル',
      'ko': '알-아스르',
      'th': 'อัล-อัศร',
    },

    {
      'ar': 'الهمزة',
      'tr': 'Hümeze',
      'en': 'Al-Humazah',
      'id': 'Al-Humazah',
      'ur': 'Al-Humazah',
      'ms': 'Al-Humazah',
      'bn': 'আল-হুমাযাহ',
      'fr': 'Al-Humazah',
      'hi': 'अल-हुमाज़ाह',
      'fa': 'الهمزه',
      'uz': 'Al-Humazah',
      'ru': 'Аль-Хумаза',
      'es': 'Al-Humazah',
      'pt': 'Al-Humazah',
      'de': 'Al-Humazah',
      'it': 'Al-Humazah',
      'zh': 'Al-Humazah',
      'sw': 'Al-Humazah',
      'ja': 'アル＝フマザ',
      'ko': '알-후마자',
      'th': 'อัล-ฮูมะซะฮ์',
    },

    {
      'ar': 'الفيل',
      'tr': 'Fîl',
      'en': 'Al-Fil',
      'id': 'Al-Fil',
      'ur': 'Al-Fil',
      'ms': 'Al-Fil',
      'bn': 'আল-ফীল',
      'fr': 'Al-Fil',
      'hi': 'अल-फील',
      'fa': 'الفیل',
      'uz': 'Al-Fil',
      'ru': 'Аль-Филь',
      'es': 'Al-Fil',
      'pt': 'Al-Fil',
      'de': 'Al-Fil',
      'it': 'Al-Fil',
      'zh': 'Al-Fil',
      'sw': 'Al-Fil',
      'ja': 'アル＝フィール',
      'ko': '알-필',
      'th': 'อัล-ฟีล',
    },

    {
      'ar': 'قريش',
      'tr': 'Kureyş',
      'en': 'Quraysh',
      'id': 'Quraysh',
      'ur': 'Quraysh',
      'ms': 'Quraysh',
      'bn': 'কুরাইশ',
      'fr': 'Quraysh',
      'hi': 'कुरैश',
      'fa': 'قریش',
      'uz': 'Quraysh',
      'ru': 'Курайш',
      'es': 'Quraysh',
      'pt': 'Quraysh',
      'de': 'Quraysh',
      'it': 'Quraysh',
      'zh': 'Quraysh',
      'sw': 'Quraysh',
      'ja': 'クライシュ',
      'ko': '쿠라이시',
      'th': 'กุราย์ช',
    },

    {
      'ar': 'الماعون',
      'tr': 'Mâûn',
      'en': 'Al-Ma\'un',
      'id': 'Al-Ma\'un',
      'ur': 'Al-Ma\'un',
      'ms': 'Al-Ma\'un',
      'bn': 'আল-মাউন',
      'fr': 'Al-Ma\'un',
      'hi': 'अल-माउ़न',
      'fa': 'الماعون',
      'uz': 'Al-Ma\'un',
      'ru': 'Аль-Ма\'ун',
      'es': 'Al-Ma\'un',
      'pt': 'Al-Ma\'un',
      'de': 'Al-Ma\'un',
      'it': 'Al-Ma\'un',
      'zh': 'Al-Ma\'un',
      'sw': 'Al-Ma\'un',
      'ja': 'アル＝マアウン',
      'ko': '알-마운',
      'th': 'อัล-มาอูน',
    },

    {
      'ar': 'الكوثر',
      'tr': 'Kevser',
      'en': 'Al-Kawthar',
      'id': 'Al-Kawthar',
      'ur': 'Al-Kawthar',
      'ms': 'Al-Kawthar',
      'bn': 'আল-কাওসার',
      'fr': 'Al-Kawthar',
      'hi': 'अल-क़ौथर',
      'fa': 'الکوثر',
      'uz': 'Al-Kawthar',
      'ru': 'Аль-Каусар',
      'es': 'Al-Kawthar',
      'pt': 'Al-Kawthar',
      'de': 'Al-Kawthar',
      'it': 'Al-Kawthar',
      'zh': 'Al-Kawthar',
      'sw': 'Al-Kawthar',
      'ja': 'アル＝カウサル',
      'ko': '알-카우사르',
      'th': 'อัล-คาวซาร์',
    },

    {
      'ar': 'الكافرون',
      'tr': 'Kâfirûn',
      'en': 'Al-Kafirun',
      'id': 'Al-Kafirun',
      'ur': 'Al-Kafirun',
      'ms': 'Al-Kafirun',
      'bn': 'আল-কাফিরূন',
      'fr': 'Al-Kafirun',
      'hi': 'अल-काफिरून',
      'fa': 'کافرون',
      'uz': 'Al-Kafirun',
      'ru': 'Аль-Кафирун',
      'es': 'Al-Kafirun',
      'pt': 'Al-Kafirun',
      'de': 'Al-Kafirun',
      'it': 'Al-Kafirun',
      'zh': 'Al-Kafirun',
      'sw': 'Al-Kafirun',
      'ja': 'アル＝カーフィルーン',
      'ko': '알-카피룬',
      'th': 'อัล-คาฟิรุน',
    },

    {
      'ar': 'النصر',
      'tr': 'Nasr',
      'en': 'An-Nasr',
      'id': 'An-Nasr',
      'ur': 'An-Nasr',
      'ms': 'An-Nasr',
      'bn': 'আন-নাসর',
      'fr': 'An-Nasr',
      'hi': 'अन-नस्र',
      'fa': 'النصر',
      'uz': 'An-Nasr',
      'ru': 'Ан-Наср',
      'es': 'An-Nasr',
      'pt': 'An-Nasr',
      'de': 'An-Nasr',
      'it': 'An-Nasr',
      'zh': 'An-Nasr',
      'sw': 'An-Nasr',
      'ja': 'アン＝ナスル',
      'ko': '안-나스르',
      'th': 'อัน-นัศร',
    },

    {
      'ar': 'المسد',
      'tr': 'Tebbet',
      'en': 'Al-Masad',
      'id': 'Al-Masad',
      'ur': 'Al-Masad',
      'ms': 'Al-Masad',
      'bn': 'আল-মাসাদ',
      'fr': 'Al-Masad',
      'hi': 'अल-मसद',
      'fa': 'المسد',
      'uz': 'Al-Masad',
      'ru': 'Аль-Масад',
      'es': 'Al-Masad',
      'pt': 'Al-Masad',
      'de': 'Al-Masad',
      'it': 'Al-Masad',
      'zh': 'Al-Masad',
      'sw': 'Al-Masad',
      'ja': 'アル＝マサド',
      'ko': '알-마사드',
      'th': 'อัล-มะซัด',
    },

    {
      'ar': 'الإخلاص',
      'tr': 'İhlâs',
      'en': 'Al-Ikhlas',
      'id': 'Al-Ikhlas',
      'ur': 'Al-Ikhlas',
      'ms': 'Al-Ikhlas',
      'bn': 'আল-ইখলাস',
      'fr': 'Al-Ikhlas',
      'hi': 'अल-इखलास',
      'fa': 'الاخلاص',
      'uz': 'Al-Ikhlas',
      'ru': 'Аль-Ихлас',
      'es': 'Al-Ikhlas',
      'pt': 'Al-Ikhlas',
      'de': 'Al-Ikhlas',
      'it': 'Al-Ikhlas',
      'zh': 'Al-Ikhlas',
      'sw': 'Al-Ikhlas',
      'ja': 'アル＝イクhlas',
      'ko': '알-이흘라스',
      'th': 'อัล-อิคลาส',
    },

    {
      'ar': 'الفلق',
      'tr': 'Felak',
      'en': 'Al-Falaq',
      'id': 'Al-Falaq',
      'ur': 'Al-Falaq',
      'ms': 'Al-Falaq',
      'bn': 'আল-ফালাক',
      'fr': 'Al-Falaq',
      'hi': 'अल-फलक़',
      'fa': 'الفلق',
      'uz': 'Al-Falaq',
      'ru': 'Аль-Фалак',
      'es': 'Al-Falaq',
      'pt': 'Al-Falaq',
      'de': 'Al-Falaq',
      'it': 'Al-Falaq',
      'zh': 'Al-Falaq',
      'sw': 'Al-Falaq',
      'ja': 'アル＝ファラク',
      'ko': '알-팔락',
      'th': 'อัล-ฟาลัก',
    },

    {
      'ar': 'الناس',
      'tr': 'Nâs',
      'en': 'An-Nas',
      'id': 'An-Nas',
      'ur': 'An-Nas',
      'ms': 'An-Nas',
      'bn': 'আন-নাস',
      'fr': 'An-Nas',
      'hi': 'अन-नास',
      'fa': 'الناس',
      'uz': 'An-Nas',
      'ru': 'Ан-Нас',
      'es': 'An-Nas',
      'pt': 'An-Nas',
      'de': 'An-Nas',
      'it': 'An-Nas',
      'zh': 'An-Nas',
      'sw': 'An-Nas',
      'ja': 'アン＝ナース',
      'ko': '안-나스',
      'th': 'อัน-นาส',
    },
  ];

  static String getSuraName(int suraIndex, String locale) {
    if (suraIndex < 0 || suraIndex >= surahNames.length) return '';

    // First, try to get the translation for the requested locale
    String? translation = surahNames[suraIndex][locale];
    if (translation != null && translation.isNotEmpty) {
      return translation;
    }

    // If requested locale is not supported or not found, fallback to English
    // All 21 languages have translations, so this should only happen for unsupported languages
    return surahNames[suraIndex]['en'] ?? surahNames[suraIndex]['ar'] ?? '';
  }

  /// Gets list of supported language codes for sura names
  static List<String> getSupportedLanguages() {
    return ['ar', 'tr', 'en', 'id', 'ur', 'ms', 'bn', 'fr', 'hi', 'fa', 'uz', 'ru', 'es', 'pt', 'de', 'it', 'zh', 'sw', 'ja', 'ko', 'th'];
  }

  /// Checks if a specific language is supported for sura names
  static bool isLanguageSupported(String locale) {
    return getSupportedLanguages().contains(locale);
  }

  static int getTotalSuras() => surahNames.length;
}
